services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  firehose:
    container_name: firehose
    image: richardr1126/cosmere-firehose
    build:
      context: ./firehose
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["python", "health_check.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - postgres
  
  scheduler:
    container_name: scheduler
    image: richardr1126/cosmere-db-scheduler
    build:
      context: ./scheduler
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - firehose

  web:
    container_name: web
    image: richardr1126/cosmere-feed
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  dbdata: