services:
  firehose:
    container_name: firehose
    image: richardr1126/firehose
    build:
      context: ./firehose
    env_file:
      - .env
    volumes:
      - feeddata:/var/data
    stdin_open: true
    tty: true

  web:
    container_name: web
    image: richardr1126/cosmere-feed
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - feeddata:/var/data
    stdin_open: true
    tty: true

volumes:
  feeddata:
