provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns
        key: cloudflare_api_token

extraArgs:
  - --exclude-target-net=192.168.0.0/16