ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: ""
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: cosmere.richardr.dev
    external-dns.alpha.kubernetes.io/target: d2fada6d-89c0-473e-a5f2-4625b2b5576d.cfargotunnel.com
  hosts:
    - ip: 192.168.0.69
      paths:
        - path: /
          pathType: Prefix