ingress:
  enabled: true
  className: "nginx"
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: cosmere.richardr.dev
    external-dns.alpha.kubernetes.io/target: 71.218.121.109
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  hosts:
    - host: cosmere.richardr.dev
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - secretName: web-tls
  #     hosts:
  #       - cosmere.richardr.dev