apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmere-feed-bsky
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/richardr1126/cosmere-feed-bsky
    targetRevision: main
    path: k8s/helm/cosmere-feed-bsky
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true