name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: richardr1126

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: web
            dockerfile: Dockerfile
            image_name: cosmere-feed
            context: .
          - name: firehose
            dockerfile: firehose/Dockerfile
            image_name: cosmere-firehose
            context: firehose
          - name: scheduler
            dockerfile: scheduler/Dockerfile
            image_name: cosmere-scheduler
            context: scheduler

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=latest,enable=${{ !contains(github.ref, '-pre') }}
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=https://github.com/richardr1126/cosmere-feed-bsky
            org.opencontainers.image.description=Cosmere Feed ${{ matrix.name }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push ${{ matrix.name }} Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}