name: Publish Feed

on:
  push:
    branches:
      - main
    paths:
      - 'publish_feed.py'
  workflow_dispatch:

jobs:
  publish-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Publish Feed Script
        env:
          HOSTNAME: ${{ secrets.HOSTNAME }}
          HANDLE: ${{ secrets.HANDLE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SERVICE_DID: ${{ secrets.SERVICE_DID }}
        run: |
          python publish_feed.py
